# =========================================================================
# 1. Configuracao Dinamica do Banco (Forcando Producao)
# =========================================================================
spring.datasource.url=jdbc:postgresql://db-rnplanner-dev.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=admin_rnplanner
spring.datasource.password=Edu@rdo3600
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================================
# 2. Configuracoes do Hibernate
# =========================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================================
# 3. Ajuste para Texto Longo
# =========================================================================
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# =========================================================================
# 4. Otimizacao de Lotes (Batch)
# =========================================================================
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

server.error.include-message=always